name: Calidad de Código Simplificada

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  frontend-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run ESLint
      run: |
        npm run lint || echo "⚠️ Linting encontró problemas"
    
    - name: Run Prettier check
      run: |
        npx prettier --check "*.{js,css,json,md}" || echo "⚠️ Formateo necesario"
    
    - name: Check file sizes
      run: |
        echo "Verificando tamaños de archivos..."
        find . -name "*.js" -o -name "*.css" -o -name "*.html" | xargs ls -lh
        echo "✅ Verificación de tamaños completada"

  basic-checks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check README
      run: |
        if [ -f "README.md" ] && [ -s "README.md" ]; then
          echo "✅ README.md existe y tiene contenido"
        else
          echo "⚠️ README.md faltante o vacío"
        fi
    
    - name: Check for TODO comments
      run: |
        echo "Buscando TODOs pendientes..."
        grep -r "TODO\|FIXME\|HACK" --include="*.js" --include="*.html" --include="*.css" . || echo "✅ No se encontraron TODOs"
    
    - name: Check for console.log statements
      run: |
        echo "Verificando console.log en producción..."
        if grep -r "console\.log" --include="*.js" .; then
          echo "⚠️ console.log encontrados - considerar remover para producción"
        else
          echo "✅ No se encontraron console.log"
        fi

  performance-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check bundle size
      run: |
        echo "Verificando tamaños de archivos principales..."
        if [ -f "index.html" ]; then
          size=$(wc -c < index.html)
          echo "index.html: $size bytes"
          if [ $size -gt 200000 ]; then
            echo "⚠️ index.html es muy grande (>200KB)"
          else
            echo "✅ Tamaño de index.html aceptable"
          fi
        fi
    
    - name: Check for large assets
      run: |
        echo "Buscando archivos grandes..."
        find . -type f -size +1M -not -path "./node_modules/*" -not -path "./.git/*" | head -10
        echo "✅ Verificación de assets completada"

