name: Deploy Simplificado

on:
  push:
    branches: [ main ]

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
    
    - name: Build frontend
      run: |
        npm run build || echo "Build no configurado, usando archivos existentes"
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        exclude_assets: |
          node_modules/
          .github/
          backend_app/
          tests/
          venv/
          __pycache__/
          *.py
          requirements*.txt
          pytest.ini

  notify:
    needs: deploy-frontend
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Notify deployment status
      run: |
        if [ "${{ needs.deploy-frontend.result }}" == "success" ]; then
          echo "✅ Deploy exitoso"
        else
          echo "❌ Deploy falló"
        fi

